### ISSUE TITLE
Add state database

### ISSUE THREAD

**Issue by audrow** [robotpt/vision-project#30]
We will need to have a persistent state database of some sort. This database should handle concurrency issues, that is being written to by several sources at the same time.

**Comment by audrow** [comment]
@emilyxzhou, what do you think of [audrow/mongodb-statedb](https://github.com/audrow/mongodb-statedb)?

I use MongoDB to handle concurrency issues. The idea is that each node needing to write to the state database would have an instance of this class. In addition to handling concurrency, this approach simplifies error handling, by doing it in the class instance, rather than having to send it to a ROS node that then sends back an error state, which would then need to be interpreted and then handled.

I imagine using ROS's parameters to set the needed host and port for this class.

**Comment by emilyxzhou** [comment]
@audrow, looks good! This MongoDB approach is much simpler than dealing with concurrency in a ROS node.

**Comment by audrow** [comment]
Great, I'll close this issue then. We can open it back up if the above approach doesn't work for us.
